-- Generado por Oracle SQL Developer Data Modeler 4.1.0.881
--   en:        2019-01-14 09:19:11 CET
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




DROP TABLE AMBIT CASCADE CONSTRAINTS ;

DROP TABLE AVALUACIO CASCADE CONSTRAINTS ;

DROP TABLE CONTEXTUALITZACIO CASCADE CONSTRAINTS ;

DROP TABLE CRITERI CASCADE CONSTRAINTS ;

DROP TABLE DIAGNOSTIC CASCADE CONSTRAINTS ;

DROP TABLE ECONOMIA CASCADE CONSTRAINTS ;

DROP TABLE ENTORN CASCADE CONSTRAINTS ;

DROP TABLE EXPEDIENT CASCADE CONSTRAINTS ;

DROP TABLE EX_REFERENCIA CASCADE CONSTRAINTS ;

DROP TABLE FACTOR CASCADE CONSTRAINTS ;

DROP TABLE FACTOR_ECONOMIC CASCADE CONSTRAINTS ;

DROP TABLE FREQUENCIA CASCADE CONSTRAINTS ;

DROP TABLE FREQUENCIA_GRAVETAT CASCADE CONSTRAINTS ;

DROP TABLE GRAVETAT CASCADE CONSTRAINTS ;

DROP TABLE PERSONA CASCADE CONSTRAINTS ;

DROP TABLE RISC CASCADE CONSTRAINTS ;

DROP TABLE SITUACIO_SOCIAL CASCADE CONSTRAINTS ;

DROP TABLE VERSIO_MODEL CASCADE CONSTRAINTS ;

CREATE TABLE AMBIT
  ( id NUMBER NOT NULL , descripcio VARCHAR2 (150)
  ) ;
ALTER TABLE AMBIT ADD CONSTRAINT AMBIT_PK PRIMARY KEY ( id ) ;

CREATE TABLE AVALUACIO
  (
    id           NUMBER NOT NULL ,
    expedient    NUMBER NOT NULL ,
    entorn       NUMBER NOT NULL ,
    professional CHAR (1) ,
    risc         NUMBER NOT NULL
  ) ;
ALTER TABLE AVALUACIO ADD CONSTRAINT AVALUACIO_PK PRIMARY KEY ( id ) ;

CREATE TABLE CONTEXTUALITZACIO
  (
    id          NUMBER NOT NULL ,
    expedient   NUMBER NOT NULL ,
    membre_unic CHAR (1) ,
    mes_UC      CHAR (1) ,
    persona     NUMBER ,
    factor      NUMBER NOT NULL
  ) ;
ALTER TABLE CONTEXTUALITZACIO ADD CONSTRAINT CONTEXTUALITZACIO_PK PRIMARY KEY ( id ) ;

CREATE TABLE CRITERI
  (
    id                  NUMBER NOT NULL ,
    evidencia           VARCHAR2 (500) ,
    frequencia          NUMBER NOT NULL ,
    risc                NUMBER NOT NULL ,
    frequencia_gravetat VARCHAR2 (32) NOT NULL
  ) ;
ALTER TABLE CRITERI ADD CONSTRAINT CRITERI_PK PRIMARY KEY ( id ) ;

CREATE TABLE DIAGNOSTIC
  (
    id              NUMBER NOT NULL ,
    expedient       NUMBER NOT NULL ,
    persona         NUMBER ,
    risc            NUMBER NOT NULL ,
    gravetat        NUMBER NOT NULL ,
    frequencia      NUMBER NOT NULL ,
    situacio_social VARCHAR2 (32) NOT NULL ,
    entorn          NUMBER NOT NULL
  ) ;
ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTICv1_PK PRIMARY KEY ( id ) ;

CREATE TABLE ECONOMIA
  (
    id        NUMBER NOT NULL ,
    expedient NUMBER NOT NULL ,
    valor     CHAR (1) ,
    factor    NUMBER NOT NULL
  ) ;
ALTER TABLE ECONOMIA ADD CONSTRAINT ECONOMIA_PK PRIMARY KEY ( id ) ;

CREATE TABLE ENTORN
  (
    id         NUMBER NOT NULL ,
    descripcio VARCHAR2 (250) ,
    ambit      NUMBER NOT NULL
  ) ;
ALTER TABLE ENTORN ADD CONSTRAINT ENTORN_PK PRIMARY KEY ( id ) ;

CREATE TABLE EXPEDIENT
  (
    id            NUMBER NOT NULL ,
    expedient     VARCHAR2 (50) NOT NULL ,
    professional  VARCHAR2 (100) ,
    nom           VARCHAR2 (100) ,
    data          TIMESTAMP WITH LOCAL TIME ZONE ,
    observacions  VARCHAR2 (250) ,
    total_familia NUMBER ,
    versio_model  NUMBER NOT NULL
  ) ;
ALTER TABLE EXPEDIENT ADD CONSTRAINT EXPEDIENT_PK PRIMARY KEY ( id ) ;

CREATE TABLE EX_REFERENCIA
  (
    expedient NUMBER NOT NULL ,
    persona   NUMBER NOT NULL
  ) ;
ALTER TABLE EX_REFERENCIA ADD CONSTRAINT EX_REFERENCIA_PK PRIMARY KEY ( expedient, persona ) ;

CREATE TABLE FACTOR
  (
    id         NUMBER NOT NULL ,
    gravetat   NUMBER NOT NULL ,
    entorn     NUMBER NOT NULL ,
    descripcio VARCHAR2 (300)
  ) ;
ALTER TABLE FACTOR ADD CONSTRAINT FACTOR_PKv2 PRIMARY KEY ( id ) ;

CREATE TABLE FACTOR_ECONOMIC
  (
    id         NUMBER NOT NULL ,
    descripcio VARCHAR2 (300)
  ) ;
ALTER TABLE FACTOR_ECONOMIC ADD CONSTRAINT FACTOR_ECONOMIC_PK PRIMARY KEY ( id ) ;

CREATE TABLE FREQUENCIA
  ( id NUMBER NOT NULL , descripcio VARCHAR2 (100)
  ) ;
ALTER TABLE FREQUENCIA ADD CONSTRAINT FREQUENCIA_PK PRIMARY KEY ( id ) ;

CREATE TABLE FREQUENCIA_GRAVETAT
  (
    id              VARCHAR2 (32) NOT NULL ,
    situacio_social VARCHAR2 (32) NOT NULL ,
    evidencia       VARCHAR2 (500) NOT NULL ,
    gravetat        NUMBER NOT NULL
  ) ;
ALTER TABLE FREQUENCIA_GRAVETAT ADD CONSTRAINT MODEL_PK PRIMARY KEY ( id ) ;

CREATE TABLE GRAVETAT
  ( id NUMBER NOT NULL , descripcio VARCHAR2 (100)
  ) ;
ALTER TABLE GRAVETAT ADD CONSTRAINT GRAVETAT_PK PRIMARY KEY ( id ) ;

CREATE TABLE PERSONA
  (
    id      NUMBER NOT NULL ,
    nom     VARCHAR2 (50) ,
    cognom1 VARCHAR2 (50) ,
    cognom2 VARCHAR2 (50)
  ) ;
ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_PK PRIMARY KEY ( id ) ;

CREATE TABLE RISC
  ( id NUMBER NOT NULL , descripcio VARCHAR2 (100)
  ) ;
ALTER TABLE RISC ADD CONSTRAINT RISC_PK PRIMARY KEY ( id ) ;

CREATE TABLE SITUACIO_SOCIAL
  (
    id             VARCHAR2 (32) NOT NULL ,
    social         VARCHAR2 (500) ,
    definicio      VARCHAR2 (600) ,
    entorn         NUMBER NOT NULL ,
    vulnerabilitat NUMBER ,
    risc           NUMBER ,
    alt_risc       NUMBER ,
    versio_model   NUMBER NOT NULL
  ) ;
ALTER TABLE SITUACIO_SOCIAL ADD CONSTRAINT SITUACIO_SOCIAL_PK PRIMARY KEY ( id ) ;

CREATE TABLE VERSIO_MODEL
  (
    id     NUMBER NOT NULL ,
    versio VARCHAR2 (20) ,
    data   TIMESTAMP WITH LOCAL TIME ZONE
  ) ;
ALTER TABLE VERSIO_MODEL ADD CONSTRAINT VERSIO_MODEL_PK PRIMARY KEY ( id ) ;

ALTER TABLE AVALUACIO ADD CONSTRAINT AVALUACIO_ENTORN_FK FOREIGN KEY ( entorn ) REFERENCES ENTORN ( id ) ;

ALTER TABLE AVALUACIO ADD CONSTRAINT AVALUACIO_EXPEDIENT_FK FOREIGN KEY ( expedient ) REFERENCES EXPEDIENT ( id ) ;

ALTER TABLE AVALUACIO ADD CONSTRAINT AVALUACIO_RISC_FK FOREIGN KEY ( risc ) REFERENCES RISC ( id ) ;

ALTER TABLE CONTEXTUALITZACIO ADD CONSTRAINT CONTX_EXPEDIENT_FK FOREIGN KEY ( expedient ) REFERENCES EXPEDIENT ( id ) ;

ALTER TABLE CONTEXTUALITZACIO ADD CONSTRAINT CONTX_FACTOR_FK FOREIGN KEY ( factor ) REFERENCES FACTOR ( id ) ;

ALTER TABLE CONTEXTUALITZACIO ADD CONSTRAINT CONTX_PERSONA_FK FOREIGN KEY ( persona ) REFERENCES PERSONA ( id ) ;

ALTER TABLE CRITERI ADD CONSTRAINT CRITERI_FREQUENCIA_FK FOREIGN KEY ( frequencia ) REFERENCES FREQUENCIA ( id ) ;

ALTER TABLE CRITERI ADD CONSTRAINT CRITERI_FREQUENCIA_GRAVETAT_FK FOREIGN KEY ( frequencia_gravetat ) REFERENCES FREQUENCIA_GRAVETAT ( id ) ;

ALTER TABLE CRITERI ADD CONSTRAINT CRITERI_RISC_FK FOREIGN KEY ( risc ) REFERENCES RISC ( id ) ;

ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTIC2_ENTORN_FK FOREIGN KEY ( entorn ) REFERENCES ENTORN ( id ) ;

ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTIC2_PERSONA_FK FOREIGN KEY ( persona ) REFERENCES PERSONA ( id ) ;

ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTIC2_SITUACIO_SOCIAL_FK FOREIGN KEY ( situacio_social ) REFERENCES SITUACIO_SOCIAL ( id ) ;

ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTICv1_EXPEDIENT_FK FOREIGN KEY ( expedient ) REFERENCES EXPEDIENT ( id ) ;

ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTICv1_FREQUENCIA_FK FOREIGN KEY ( frequencia ) REFERENCES FREQUENCIA ( id ) ;

ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTICv1_GRAVETAT_FK FOREIGN KEY ( gravetat ) REFERENCES GRAVETAT ( id ) ;

ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTICv1_RISC_FK FOREIGN KEY ( risc ) REFERENCES RISC ( id ) ;

ALTER TABLE ECONOMIA ADD CONSTRAINT ECONOMIA_EXPEDIENT_FK FOREIGN KEY ( expedient ) REFERENCES EXPEDIENT ( id ) ;

ALTER TABLE ECONOMIA ADD CONSTRAINT ECONOMIA_FACTOR_ECONOMIC_FK FOREIGN KEY ( factor ) REFERENCES FACTOR_ECONOMIC ( id ) ;

ALTER TABLE ENTORN ADD CONSTRAINT ENTORN_AMBIT_FK FOREIGN KEY ( ambit ) REFERENCES AMBIT ( id ) ;

ALTER TABLE EXPEDIENT ADD CONSTRAINT EXPEDIENT_VERSIO_MODEL_FK FOREIGN KEY ( versio_model ) REFERENCES VERSIO_MODEL ( id ) ;

ALTER TABLE EX_REFERENCIA ADD CONSTRAINT EX_REFERENCIA_EXPEDIENT_FK FOREIGN KEY ( expedient ) REFERENCES EXPEDIENT ( id ) ;

ALTER TABLE EX_REFERENCIA ADD CONSTRAINT EX_REFERENCIA_PERSONA_FK FOREIGN KEY ( persona ) REFERENCES PERSONA ( id ) ;

ALTER TABLE FACTOR ADD CONSTRAINT FACTOR_ENTORN_FK FOREIGN KEY ( entorn ) REFERENCES ENTORN ( id ) ;

ALTER TABLE FACTOR ADD CONSTRAINT FACTOR_GRAVETAT_FK FOREIGN KEY ( gravetat ) REFERENCES GRAVETAT ( id ) ;

ALTER TABLE FREQUENCIA_GRAVETAT ADD CONSTRAINT FREQ_GRAVETAT_FK FOREIGN KEY ( gravetat ) REFERENCES GRAVETAT ( id ) ;

ALTER TABLE FREQUENCIA_GRAVETAT ADD CONSTRAINT FREQ_SITUACIO_SOCIAL_FK FOREIGN KEY ( situacio_social ) REFERENCES SITUACIO_SOCIAL ( id ) ;

ALTER TABLE SITUACIO_SOCIAL ADD CONSTRAINT SITUACIO_SOCIAL_ENTORN_FK FOREIGN KEY ( entorn ) REFERENCES ENTORN ( id ) ;

ALTER TABLE SITUACIO_SOCIAL ADD CONSTRAINT SITUACIO_SOCIAL_VERSIO_FK FOREIGN KEY ( versio_model ) REFERENCES VERSIO_MODEL ( id ) ;


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            18
-- CREATE INDEX                             0
-- ALTER TABLE                             46
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
