-- Generado por Oracle SQL Developer Data Modeler 4.1.0.881
--   en:        2019-03-18 14:31:27 CET
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




DROP TABLE AMBIT CASCADE CONSTRAINTS ;

DROP TABLE AMBIT_DIAGNOSTIC CASCADE CONSTRAINTS ;

DROP TABLE AVALUACIO CASCADE CONSTRAINTS ;

DROP TABLE CONTEXTUALITZACIO CASCADE CONSTRAINTS ;

DROP TABLE CRITERI CASCADE CONSTRAINTS ;

DROP TABLE DIAGNOSTIC CASCADE CONSTRAINTS ;

DROP TABLE ECONOMIA CASCADE CONSTRAINTS ;

DROP TABLE ENTORN CASCADE CONSTRAINTS ;

DROP TABLE ESTAT CASCADE CONSTRAINTS ;

DROP TABLE EXPEDIENT CASCADE CONSTRAINTS ;

DROP TABLE FACTOR CASCADE CONSTRAINTS ;

DROP TABLE FACTOR_ECONOMIC CASCADE CONSTRAINTS ;

DROP TABLE FREQUENCIA CASCADE CONSTRAINTS ;

DROP TABLE FREQUENCIA_GRAVETAT CASCADE CONSTRAINTS ;

DROP TABLE GRAVETAT CASCADE CONSTRAINTS ;

DROP TABLE MUNICIPI CASCADE CONSTRAINTS ;

DROP TABLE PERSONA CASCADE CONSTRAINTS ;

DROP TABLE PREGUNTA CASCADE CONSTRAINTS ;

DROP TABLE PROFESSIONAL CASCADE CONSTRAINTS ;

DROP TABLE PROFESSIONAL_ROL CASCADE CONSTRAINTS ;

DROP TABLE RISC CASCADE CONSTRAINTS ;

DROP TABLE ROL CASCADE CONSTRAINTS ;

DROP TABLE SITUACIO_SOCIAL CASCADE CONSTRAINTS ;

DROP TABLE TIPUS_PERSONA CASCADE CONSTRAINTS ;

DROP TABLE VALORACIO CASCADE CONSTRAINTS ;

DROP TABLE VERSIO_MODEL CASCADE CONSTRAINTS ;

CREATE TABLE AMBIT
  (
    id                 NUMBER NOT NULL ,
    descripcio         VARCHAR2 (150) ,
    vulnerabilitat     NUMBER ,
    risc               NUMBER ,
    val_vulnerabilitat NUMBER ,
    val_risc           NUMBER ,
    val_altrisc        NUMBER ,
    observacions       VARCHAR2 (500) ,
    versio_model       NUMBER NOT NULL
  ) ;
ALTER TABLE AMBIT ADD CONSTRAINT AMBIT_PK PRIMARY KEY ( id ) ;

CREATE TABLE AMBIT_DIAGNOSTIC
  (
    id           NUMBER NOT NULL ,
    ambit        NUMBER NOT NULL ,
    diagnostic   NUMBER ,
    observacions VARCHAR2 (250)
  ) ;
ALTER TABLE AMBIT_DIAGNOSTIC ADD CONSTRAINT AMBIT_DIAGNOSTIC_PK PRIMARY KEY ( id ) ;

CREATE TABLE AVALUACIO
  (
    id                NUMBER NOT NULL ,
    risc_professional NUMBER ,
    risc              NUMBER ,
    valoracio         NUMBER ,
    ambit             NUMBER ,
    justificacio      VARCHAR2 (250)
  ) ;
ALTER TABLE AVALUACIO ADD CONSTRAINT AVALUACIO_PK PRIMARY KEY ( id ) ;

CREATE TABLE CONTEXTUALITZACIO
  (
    id          NUMBER NOT NULL ,
    diagnostic  NUMBER NOT NULL ,
    membre_unic CHAR (1) ,
    mes_UC      CHAR (1) ,
    persona     NUMBER ,
    factor      NUMBER NOT NULL
  ) ;
ALTER TABLE CONTEXTUALITZACIO ADD CONSTRAINT CONTEXTUALITZACIO_PK PRIMARY KEY ( id ) ;

CREATE TABLE CRITERI
  (
    id                  NUMBER NOT NULL ,
    evidencia           VARCHAR2 (500) ,
    frequencia          NUMBER NOT NULL ,
    risc                NUMBER NOT NULL ,
    frequencia_gravetat VARCHAR2 (32) NOT NULL
  ) ;
ALTER TABLE CRITERI ADD CONSTRAINT CRITERI_PK PRIMARY KEY ( id ) ;

CREATE TABLE DIAGNOSTIC
  (
    id           NUMBER NOT NULL ,
    data         TIMESTAMP WITH LOCAL TIME ZONE ,
    observacions VARCHAR2 (250) ,
    versio_model NUMBER ,
    valoracio    NUMBER ,
    expedient    NUMBER ,
    estat        NUMBER ,
    professional NUMBER
  ) ;
ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTIC_PK PRIMARY KEY ( id ) ;

CREATE TABLE ECONOMIA
  ( factor NUMBER NOT NULL , pregunta NUMBER NOT NULL
  ) ;
ALTER TABLE ECONOMIA ADD CONSTRAINT ECONOMIA_PK PRIMARY KEY ( factor, pregunta ) ;

CREATE TABLE ENTORN
  (
    id         NUMBER NOT NULL ,
    descripcio VARCHAR2 (250) ,
    ambit      NUMBER NOT NULL
  ) ;
ALTER TABLE ENTORN ADD CONSTRAINT ENTORN_PK PRIMARY KEY ( id ) ;

CREATE TABLE ESTAT
  ( id NUMBER NOT NULL , descripcio VARCHAR2 (50)
  ) ;
ALTER TABLE ESTAT ADD CONSTRAINT ESTAT_PK PRIMARY KEY ( id ) ;

CREATE TABLE EXPEDIENT
  (
    id             NUMBER NOT NULL ,
    codi           VARCHAR2 (50) NOT NULL ,
    data_creacio   TIMESTAMP WITH LOCAL TIME ZONE ,
    total_familia  NUMBER ,
    professional   NUMBER ,
    total          NUMBER ,
    data_validacio TIMESTAMP WITH LOCAL TIME ZONE ,
    estat          NUMBER ,
    observacions   VARCHAR2 (500)
  ) ;
ALTER TABLE EXPEDIENT ADD CONSTRAINT EXPEDIENT_PK PRIMARY KEY ( id ) ;

CREATE TABLE FACTOR
  (
    id         NUMBER NOT NULL ,
    gravetat   NUMBER ,
    descripcio VARCHAR2 (300) ,
    fc1m       NUMBER ,
    fctots     NUMBER ,
    ambit      NUMBER ,
    infants    CHAR (1)
  ) ;
ALTER TABLE FACTOR ADD CONSTRAINT FACTOR_PKv2 PRIMARY KEY ( id ) ;

CREATE TABLE FACTOR_ECONOMIC
  (
    id           NUMBER NOT NULL ,
    descripcio   VARCHAR2 (300) ,
    versio_model NUMBER NOT NULL
  ) ;
ALTER TABLE FACTOR_ECONOMIC ADD CONSTRAINT FACTOR_ECONOMIC_PK PRIMARY KEY ( id ) ;

CREATE TABLE FREQUENCIA
  (
    id         NUMBER NOT NULL ,
    descripcio VARCHAR2 (100) ,
    value      INTEGER
  ) ;
ALTER TABLE FREQUENCIA ADD CONSTRAINT FREQUENCIA_PK PRIMARY KEY ( id ) ;

CREATE TABLE FREQUENCIA_GRAVETAT
  (
    id              VARCHAR2 (32) NOT NULL ,
    situacio_social VARCHAR2 (32) NOT NULL ,
    evidencia       VARCHAR2 (500) NOT NULL ,
    gravetat        NUMBER NOT NULL
  ) ;
ALTER TABLE FREQUENCIA_GRAVETAT ADD CONSTRAINT MODEL_PK PRIMARY KEY ( id ) ;

CREATE TABLE GRAVETAT
  (
    id         NUMBER NOT NULL ,
    descripcio VARCHAR2 (100) ,
    value      INTEGER
  ) ;
ALTER TABLE GRAVETAT ADD CONSTRAINT GRAVETAT_PK PRIMARY KEY ( id ) ;

CREATE TABLE MUNICIPI
  ( id NUMBER NOT NULL , descripcio VARCHAR2 (100)
  ) ;
ALTER TABLE MUNICIPI ADD CONSTRAINT MUNICIPI_PK PRIMARY KEY ( id ) ;

CREATE TABLE PERSONA
  (
    id             NUMBER NOT NULL ,
    sexe           VARCHAR2 (10) ,
    data_naixement TIMESTAMP WITH LOCAL TIME ZONE ,
    tipus_persona  NUMBER ,
    referencia     CHAR (1) ,
    data_alta      TIMESTAMP WITH LOCAL TIME ZONE ,
    data_baixa     TIMESTAMP WITH LOCAL TIME ZONE ,
    expedient      NUMBER
  ) ;
ALTER TABLE PERSONA ADD CONSTRAINT tipus_persona PRIMARY KEY ( id ) ;

CREATE TABLE PREGUNTA
  (
    id              NUMBER NOT NULL ,
    diagnostic      NUMBER ,
    persona         NUMBER ,
    risc            NUMBER ,
    gravetat        NUMBER ,
    frequencia      NUMBER ,
    situacio_social VARCHAR2 (32) ,
    entorn          NUMBER ,
    unitat_familiar CHAR (1) ,
    factor          NUMBER ,
    ambit           NUMBER
  ) ;
ALTER TABLE PREGUNTA ADD CONSTRAINT DIAGNOSTICv1_PK PRIMARY KEY ( id ) ;

CREATE TABLE PROFESSIONAL
  (
    id          NUMBER NOT NULL ,
    nom         VARCHAR2 (100) ,
    cognom1     VARCHAR2 (100) ,
    cognom2     VARCHAR2 (100) ,
    municipi    NUMBER NOT NULL ,
    nom_complet VARCHAR2 (100)
  ) ;
ALTER TABLE PROFESSIONAL ADD CONSTRAINT PROFESSIONAL_PK PRIMARY KEY ( id ) ;

CREATE TABLE PROFESSIONAL_ROL
  (
    professional NUMBER NOT NULL ,
    rol          NUMBER NOT NULL
  ) ;
ALTER TABLE PROFESSIONAL_ROL ADD CONSTRAINT PROFESSIONAL_ROL_PK PRIMARY KEY ( professional, rol ) ;

CREATE TABLE RISC
  (
    id         NUMBER NOT NULL ,
    descripcio VARCHAR2 (100) ,
    value      INTEGER
  ) ;
ALTER TABLE RISC ADD CONSTRAINT RISC_PK PRIMARY KEY ( id ) ;

CREATE TABLE ROL
  ( id NUMBER NOT NULL , descripcio VARCHAR2 (30)
  ) ;
ALTER TABLE ROL ADD CONSTRAINT ROL_PK PRIMARY KEY ( id ) ;

CREATE TABLE SITUACIO_SOCIAL
  (
    id             VARCHAR2 (32) NOT NULL ,
    social         VARCHAR2 (500) ,
    definicio      VARCHAR2 (600) ,
    entorn         NUMBER NOT NULL ,
    vulnerabilitat NUMBER ,
    risc           NUMBER ,
    alt_risc       NUMBER ,
    versio_model   NUMBER NOT NULL
  ) ;
ALTER TABLE SITUACIO_SOCIAL ADD CONSTRAINT SITUACIO_SOCIAL_PK PRIMARY KEY ( id ) ;

CREATE TABLE TIPUS_PERSONA
  ( id NUMBER NOT NULL , descripcio VARCHAR2 (50)
  ) ;
ALTER TABLE TIPUS_PERSONA ADD CONSTRAINT TIPUS_PERSONA_PK PRIMARY KEY ( id ) ;

CREATE TABLE VALORACIO
  (
    id        NUMBER NOT NULL ,
    total     NUMBER ,
    factors   NUMBER ,
    data      TIMESTAMP WITH LOCAL TIME ZONE ,
    confirmat CHAR (1)
  ) ;
ALTER TABLE VALORACIO ADD CONSTRAINT VALORACIO_PK PRIMARY KEY ( id ) ;

CREATE TABLE VERSIO_MODEL
  (
    id                 NUMBER NOT NULL ,
    versio             VARCHAR2 (20) ,
    data               TIMESTAMP WITH LOCAL TIME ZONE ,
    pregunta_economica NUMBER
  ) ;
ALTER TABLE VERSIO_MODEL ADD CONSTRAINT VERSIO_MODEL_PK PRIMARY KEY ( id ) ;

ALTER TABLE AMBIT_DIAGNOSTIC ADD CONSTRAINT AMBIT_DIAGNOSTIC_AMBIT_FK FOREIGN KEY ( ambit ) REFERENCES AMBIT ( id ) ;

ALTER TABLE AMBIT_DIAGNOSTIC ADD CONSTRAINT AMBIT_DIAGNOSTIC_DIAGNOSTIC_FK FOREIGN KEY ( diagnostic ) REFERENCES DIAGNOSTIC ( id ) ;

ALTER TABLE AMBIT ADD CONSTRAINT AMBIT_VERSIO_MODEL_FK FOREIGN KEY ( versio_model ) REFERENCES VERSIO_MODEL ( id ) ;

ALTER TABLE AVALUACIO ADD CONSTRAINT AVALUACIO_AMBIT_DIAGNOSTIC_FK FOREIGN KEY ( ambit ) REFERENCES AMBIT_DIAGNOSTIC ( id ) ;

ALTER TABLE AVALUACIO ADD CONSTRAINT AVALUACIO_RISC_FK FOREIGN KEY ( risc ) REFERENCES RISC ( id ) ;

ALTER TABLE AVALUACIO ADD CONSTRAINT AVALUACIO_RISC_PROF_FK FOREIGN KEY ( risc_professional ) REFERENCES RISC ( id ) ;

ALTER TABLE AVALUACIO ADD CONSTRAINT AVALUACIO_VALORACIO_FK FOREIGN KEY ( valoracio ) REFERENCES VALORACIO ( id ) ;

ALTER TABLE CONTEXTUALITZACIO ADD CONSTRAINT CONTX_DIAGNOSTIC_FK FOREIGN KEY ( diagnostic ) REFERENCES DIAGNOSTIC ( id ) ;

ALTER TABLE CONTEXTUALITZACIO ADD CONSTRAINT CONTX_FACTOR_FK FOREIGN KEY ( factor ) REFERENCES FACTOR ( id ) ;

ALTER TABLE CONTEXTUALITZACIO ADD CONSTRAINT CONTX_PERSONA_FK FOREIGN KEY ( persona ) REFERENCES PERSONA ( id ) ;

ALTER TABLE CRITERI ADD CONSTRAINT CRITERI_FREQUENCIA_FK FOREIGN KEY ( frequencia ) REFERENCES FREQUENCIA ( id ) ;

ALTER TABLE CRITERI ADD CONSTRAINT CRITERI_FREQUENCIA_GRAVETAT_FK FOREIGN KEY ( frequencia_gravetat ) REFERENCES FREQUENCIA_GRAVETAT ( id ) ;

ALTER TABLE CRITERI ADD CONSTRAINT CRITERI_RISC_FK FOREIGN KEY ( risc ) REFERENCES RISC ( id ) ;

ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTIC_ESTAT_FK FOREIGN KEY ( estat ) REFERENCES ESTAT ( id ) ;

ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTIC_EXPEDIENT_FK FOREIGN KEY ( expedient ) REFERENCES EXPEDIENT ( id ) ;

ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTIC_PROFESSIONAL_FK FOREIGN KEY ( professional ) REFERENCES PROFESSIONAL ( id ) ;

ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTIC_VALORACIO_FK FOREIGN KEY ( valoracio ) REFERENCES VALORACIO ( id ) ;

ALTER TABLE DIAGNOSTIC ADD CONSTRAINT DIAGNOSTIC_VERSIO_MODEL_FK FOREIGN KEY ( versio_model ) REFERENCES VERSIO_MODEL ( id ) ;

ALTER TABLE ECONOMIA ADD CONSTRAINT ECONOMIA_FACTOR_ECONOMIC_FK FOREIGN KEY ( factor ) REFERENCES FACTOR_ECONOMIC ( id ) ;

ALTER TABLE ECONOMIA ADD CONSTRAINT ECONOMIA_PREGUNTA_FK FOREIGN KEY ( pregunta ) REFERENCES PREGUNTA ( id ) ;

ALTER TABLE ENTORN ADD CONSTRAINT ENTORN_AMBIT_FK FOREIGN KEY ( ambit ) REFERENCES AMBIT ( id ) ;

ALTER TABLE EXPEDIENT ADD CONSTRAINT EXPEDIENT_ESTAT_FK FOREIGN KEY ( estat ) REFERENCES ESTAT ( id ) ;

ALTER TABLE EXPEDIENT ADD CONSTRAINT EXPEDIENT_PROFESSIONAL_FKv2 FOREIGN KEY ( professional ) REFERENCES PROFESSIONAL ( id ) ;

ALTER TABLE FACTOR ADD CONSTRAINT FACTOR_AMBIT_FK FOREIGN KEY ( ambit ) REFERENCES AMBIT ( id ) ;

ALTER TABLE FACTOR_ECONOMIC ADD CONSTRAINT FACTOR_ECONOMIC_VERSIO_FK FOREIGN KEY ( versio_model ) REFERENCES VERSIO_MODEL ( id ) ;

ALTER TABLE FACTOR ADD CONSTRAINT FACTOR_GRAVETAT_FK FOREIGN KEY ( gravetat ) REFERENCES GRAVETAT ( id ) ;

ALTER TABLE FREQUENCIA_GRAVETAT ADD CONSTRAINT FREQ_GRAVETAT_FK FOREIGN KEY ( gravetat ) REFERENCES GRAVETAT ( id ) ;

ALTER TABLE FREQUENCIA_GRAVETAT ADD CONSTRAINT FREQ_SITUACIO_SOCIAL_FK FOREIGN KEY ( situacio_social ) REFERENCES SITUACIO_SOCIAL ( id ) ;

ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_EXPEDIENT_FK FOREIGN KEY ( expedient ) REFERENCES EXPEDIENT ( id ) ;

ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_TIPUS_PERSONA_FK FOREIGN KEY ( tipus_persona ) REFERENCES TIPUS_PERSONA ( id ) ;

ALTER TABLE PREGUNTA ADD CONSTRAINT PREGUNTA_AMBIT_DIAGNOSTIC_FK FOREIGN KEY ( ambit ) REFERENCES AMBIT_DIAGNOSTIC ( id ) ;

ALTER TABLE PREGUNTA ADD CONSTRAINT PREGUNTA_DIAGNOSTIC_FK FOREIGN KEY ( diagnostic ) REFERENCES DIAGNOSTIC ( id ) ;

ALTER TABLE PREGUNTA ADD CONSTRAINT PREGUNTA_FACTOR_FK FOREIGN KEY ( factor ) REFERENCES RISC ( id ) ;

ALTER TABLE PREGUNTA ADD CONSTRAINT PREGUNTA_FREQUENCIA_FK FOREIGN KEY ( frequencia ) REFERENCES FREQUENCIA ( id ) ;

ALTER TABLE PREGUNTA ADD CONSTRAINT PREGUNTA_GRAVETAT_FK FOREIGN KEY ( gravetat ) REFERENCES GRAVETAT ( id ) ;

ALTER TABLE PREGUNTA ADD CONSTRAINT PREGUNTA_PERSONA_FK FOREIGN KEY ( persona ) REFERENCES PERSONA ( id ) ;

ALTER TABLE PREGUNTA ADD CONSTRAINT PREGUNTA_RISC_FK FOREIGN KEY ( risc ) REFERENCES RISC ( id ) ;

ALTER TABLE PREGUNTA ADD CONSTRAINT PREGUNTA_SITUACIO_SOCIAL_FK FOREIGN KEY ( situacio_social ) REFERENCES SITUACIO_SOCIAL ( id ) ;

ALTER TABLE PROFESSIONAL ADD CONSTRAINT PROFESSIONAL_MUNICIPI_FK FOREIGN KEY ( municipi ) REFERENCES MUNICIPI ( id ) ;

ALTER TABLE PROFESSIONAL_ROL ADD CONSTRAINT PROFESSIONAL_ROL_PRO_FK FOREIGN KEY ( professional ) REFERENCES PROFESSIONAL ( id ) ;

ALTER TABLE PROFESSIONAL_ROL ADD CONSTRAINT PROFESSIONAL_ROL_ROL_FK FOREIGN KEY ( rol ) REFERENCES ROL ( id ) ;

ALTER TABLE SITUACIO_SOCIAL ADD CONSTRAINT SITUACIO_SOCIAL_ARISC_FK FOREIGN KEY ( entorn ) REFERENCES ENTORN ( id ) ;

ALTER TABLE SITUACIO_SOCIAL ADD CONSTRAINT SITUACIO_SOCIAL_RISC_FK FOREIGN KEY ( versio_model ) REFERENCES VERSIO_MODEL ( id ) ;


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            26
-- CREATE INDEX                             0
-- ALTER TABLE                             69
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
