CREATE OR REPLACE PUBLIC SYNONYM "DIBA_PRF_PROFESSIONAL" FOR "DSDIBA"."DIBA_PRF_PROFESSIONAL";
CREATE OR REPLACE PUBLIC SYNONYM "DIBA_PRR_PROFESSIONAL_ROL" FOR "DSDIBA"."DIBA_PRR_PROFESSIONAL_ROL";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_AMB_AMBIT" FOR "DSDIBA"."DIBA_AMB_AMBIT";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_AMD_AMBITDIAGNOSTIC" FOR "DSDIBA"."DIBA_AMD_AMBITDIAGNOSTIC";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_AVL_AVALUACIO" FOR "DSDIBA"."DIBA_AVL_AVALUACIO";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_CTX_CONTEXTUALITZACIO" FOR "DSDIBA"."DIBA_CTX_CONTEXTUALITZACIO";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_CRI_CRITERI" FOR "DSDIBA"."DIBA_CRI_CRITERI";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_DGC_DIAGNOSTIC" FOR "DSDIBA"."DIBA_DGC_DIAGNOSTIC";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_ECO_ECONOMIA" FOR "DSDIBA"."DIBA_ECO_ECONOMIA";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_ENT_ENTORN" FOR "DSDIBA"."DIBA_ENT_ENTORN";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_EST_ESTAT" FOR "DSDIBA"."DIBA_EST_ESTAT";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_EXP_EXPEDIENT" FOR "DSDIBA"."DIBA_EXP_EXPEDIENT";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_FCT_FACTOR" FOR "DSDIBA"."DIBA_FCT_FACTOR";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_FAE_FACTORECONOMIC" FOR "DSDIBA"."DIBA_FAE_FACTORECONOMIC";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_FRQ_FREQUENCIA" FOR "DSDIBA"."DIBA_FRQ_FREQUENCIA";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_FRG_FREQUENCIAGRAVETAT" FOR "DSDIBA"."DIBA_FRG_FREQUENCIAGRAVETAT";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_GRA_GRAVETAT" FOR "DSDIBA"."DIBA_GRA_GRAVETAT";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_MUN_MUNICIPI" FOR "DSDIBA"."DIBA_MUN_MUNICIPI";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_PER_PERSONA" FOR "DSDIBA"."DIBA_PER_PERSONA";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_PRE_PREGUNTA" FOR "DSDIBA"."DIBA_PRE_PREGUNTA";


CREATE OR REPLACE PUBLIC SYNONYM "DIBA_RIS_RISC" FOR "DSDIBA"."DIBA_RIS_RISC";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_ROL_ROL" FOR "DSDIBA"."DIBA_ROL_ROL";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_SSO_SITUACIO_SOCIAL" FOR "DSDIBA"."DIBA_SSO_SITUACIO_SOCIAL";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_TPE_TIPUSPERSONA" FOR "DSDIBA"."DIBA_TPE_TIPUSPERSONA";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_VAL_VALORACIO" FOR "DSDIBA"."DIBA_VAL_VALORACIO";

CREATE OR REPLACE PUBLIC SYNONYM "DIBA_VSM_VERSIOMODEL" FOR "DSDIBA"."DIBA_VSM_VERSIOMODEL";