ALTER TABLE DIBA_AMB_AMBIT ADD CONSTRAINT DIBA_AMB_AMBIT_PK PRIMARY KEY ( DIBA_AMB_ID ) ;

ALTER TABLE DIBA_AMD_AMBITDIAGNOSTIC ADD CONSTRAINT DIBA_AMD_AMBITDIAGNOSTIC_PK PRIMARY KEY ( DIBA_AMD_ID ) ;

ALTER TABLE DIBA_AVL_AVALUACIO ADD CONSTRAINT DIBA_AVL_AVALUACIO_PK PRIMARY KEY ( DIBA_AVL_ID ) ;

ALTER TABLE DIBA_CTX_CONTEXTUALITZACIO ADD CONSTRAINT DIBA_CTX_CONTEXTUALITZACIO_PK PRIMARY KEY ( DIBA_CTX_ID ) ;

ALTER TABLE DIBA_CRI_CRITERI ADD CONSTRAINT DIBA_CRI_CRITERI_PK PRIMARY KEY ( DIBA_CRI_ID ) ;

ALTER TABLE DIBA_DGC_DIAGNOSTIC ADD CONSTRAINT DIBA_DGC_DIAGNOSTIC_PK PRIMARY KEY ( DIBA_DGC_ID ) ;

ALTER TABLE DIBA_ECO_ECONOMIA ADD CONSTRAINT DIBA_ECO_ECONOMIA_PK PRIMARY KEY ( DIBA_ECO_FACTOR, DIBA_ECO_PREGUNTA ) ;

ALTER TABLE DIBA_ENT_ENTORN ADD CONSTRAINT DIBA_ENT_ENTORN_PK PRIMARY KEY ( DIBA_ENT_ID ) ;

ALTER TABLE DIBA_EST_ESTAT ADD CONSTRAINT DIBA_EST_ESTAT_PK PRIMARY KEY ( DIBA_EST_ID ) ;

ALTER TABLE DIBA_EXP_EXPEDIENT ADD CONSTRAINT DIBA_EXP_EXPEDIENT_PK PRIMARY KEY ( DIBA_EXP_ID ) ;

ALTER TABLE DIBA_FCT_FACTOR ADD CONSTRAINT DIBA_FCT_FACTOR_PK PRIMARY KEY ( DIBA_FCT_ID ) ;

ALTER TABLE DIBA_FAE_FACTORECONOMIC ADD CONSTRAINT DIBA_FAE_FACTORECONOMIC_PK PRIMARY KEY ( DIBA_FAE_ID ) ;

ALTER TABLE DIBA_FRQ_FREQUENCIA ADD CONSTRAINT DIBA_FRQ_FREQUENCIA_PK PRIMARY KEY ( DIBA_FRQ_ID ) ;

ALTER TABLE DIBA_FRG_FREQUENCIAGRAVETAT ADD CONSTRAINT DIBA_FRG_FREQUENCIAGRAVETAT_PK PRIMARY KEY ( DIBA_FRG_ID ) ;

ALTER TABLE DIBA_GRA_GRAVETAT ADD CONSTRAINT DIBA_GRA_GRAVETAT_PK PRIMARY KEY ( DIBA_GRA_ID ) ;

ALTER TABLE DIBA_MUN_MUNICIPI ADD CONSTRAINT DIBA_MUN_MUNICIPI_PK PRIMARY KEY ( DIBA_MUN_ID ) ;

ALTER TABLE DIBA_PER_PERSONA ADD CONSTRAINT DIBA_PER_PERSONA_PK PRIMARY KEY ( DIBA_PER_ID ) ;

ALTER TABLE DIBA_PRE_PREGUNTA ADD CONSTRAINT DIBA_PRE_PREGUNTA_PK PRIMARY KEY ( DIBA_PRE_ID ) ;

ALTER TABLE DIBA_PRF_PROFESSIONAL ADD CONSTRAINT DIBA_PRF_PROFESSIONAL_PK PRIMARY KEY ( DIBA_PRF_ID ) ;

ALTER TABLE DIBA_PRR_PROFESSIONAL_ROL ADD CONSTRAINT DIBA_PRR_PROFESSIONAL_ROL_PK PRIMARY KEY ( DIBA_PRR_PROFESSIONAL, DIBA_PRR_ROL ) ;

ALTER TABLE DIBA_RIS_RISC ADD CONSTRAINT DIBA_RIS_RISC_PK PRIMARY KEY ( DIBA_RIS_ID ) ;

ALTER TABLE DIBA_ROL_ROL ADD CONSTRAINT DIBA_ROL_ROL_PK PRIMARY KEY ( DIBA_ROL_ID ) ;

ALTER TABLE DIBA_SSO_SITUACIO_SOCIAL ADD CONSTRAINT DIBA_SSO_SITUACIO_SOCIAL_PK PRIMARY KEY ( DIBA_SSO_ID ) ;

ALTER TABLE DIBA_TPE_TIPUSPERSONA ADD CONSTRAINT DIBA_TPE_TIPUSPERSONA_PK PRIMARY KEY ( DIBA_TPE_ID ) ;

ALTER TABLE DIBA_VAL_VALORACIO ADD CONSTRAINT DIBA_VAL_VALORACIO_PK PRIMARY KEY ( DIBA_VAL_ID ) ;

ALTER TABLE DIBA_VSM_VERSIOMODEL ADD CONSTRAINT DIBA_VSM_VERSIOMODEL_PK PRIMARY KEY ( DIBA_VSM_ID ) ;

ALTER TABLE DIBA_AMD_AMBITDIAGNOSTIC ADD CONSTRAINT DIBA_AMD_FK_AMB FOREIGN KEY ( DIBA_AMD_AMBIT ) REFERENCES DIBA_AMB_AMBIT ( DIBA_AMB_ID ) ;

ALTER TABLE DIBA_AMD_AMBITDIAGNOSTIC ADD CONSTRAINT DIBA_AMD_FK_DGC FOREIGN KEY ( DIBA_AMD_DIAGNOSTIC ) REFERENCES DIBA_DGC_DIAGNOSTIC ( DIBA_DGC_ID ) ;

ALTER TABLE DIBA_AMB_AMBIT ADD CONSTRAINT DIBA_AMB_AMBIT_FK_VSM FOREIGN KEY ( DIBA_AMB_VERSIO_MODEL ) REFERENCES DIBA_VSM_VERSIOMODEL ( DIBA_VSM_ID ) ;

ALTER TABLE DIBA_AVL_AVALUACIO ADD CONSTRAINT DIBA_AVL_AVALUACIO_FK_AMD FOREIGN KEY ( DIBA_AVL_AMBIT ) REFERENCES DIBA_AMD_AMBITDIAGNOSTIC ( DIBA_AMD_ID ) ;

ALTER TABLE DIBA_AVL_AVALUACIO ADD CONSTRAINT DIBA_AVL_AVALUACIO_FK_RIS FOREIGN KEY ( DIBA_AVL_RISC ) REFERENCES DIBA_RIS_RISC ( DIBA_RIS_ID ) ;

ALTER TABLE DIBA_AVL_AVALUACIO ADD CONSTRAINT DIBA_AVL_AVALUACIO_FK_RIS_PROF FOREIGN KEY ( DIBA_AVL_RISC_PROFESSIONAL ) REFERENCES DIBA_RIS_RISC ( DIBA_RIS_ID ) ;

ALTER TABLE DIBA_AVL_AVALUACIO ADD CONSTRAINT DIBA_AVL_AVALUACIO_FK_VAL FOREIGN KEY ( DIBA_AVL_VALORACIO ) REFERENCES DIBA_VAL_VALORACIO ( DIBA_VAL_ID ) ;

ALTER TABLE DIBA_CTX_CONTEXTUALITZACIO ADD CONSTRAINT DIBA_CTX_FK_DGC FOREIGN KEY ( DIBA_CTX_DIAGNOSTIC ) REFERENCES DIBA_DGC_DIAGNOSTIC ( DIBA_DGC_ID ) ;

ALTER TABLE DIBA_CTX_CONTEXTUALITZACIO ADD CONSTRAINT DIBA_CTX_FK_FCT FOREIGN KEY ( DIBA_CTX_FACTOR ) REFERENCES DIBA_FCT_FACTOR ( DIBA_FCT_ID ) ;

ALTER TABLE DIBA_CTX_CONTEXTUALITZACIO ADD CONSTRAINT DIBA_CTX_FK_PER FOREIGN KEY ( DIBA_CTX_PERSONA ) REFERENCES DIBA_PER_PERSONA ( DIBA_PER_ID ) ;

ALTER TABLE DIBA_CRI_CRITERI ADD CONSTRAINT DIBA_CRI_CRITERI_FK_FRQ FOREIGN KEY ( DIBA_CRI_FREQUENCIA ) REFERENCES DIBA_FRQ_FREQUENCIA ( DIBA_FRQ_ID ) ;

ALTER TABLE DIBA_CRI_CRITERI ADD CONSTRAINT DIBA_CRI_CRITERI_FK_FRG FOREIGN KEY ( DIBA_CRI_FREQUENCIA_GRAVETAT ) REFERENCES DIBA_FRG_FREQUENCIAGRAVETAT ( DIBA_FRG_ID ) ;

ALTER TABLE DIBA_CRI_CRITERI ADD CONSTRAINT DIBA_CRI_CRITERI_FK_RIS FOREIGN KEY ( DIBA_CRI_RISC ) REFERENCES DIBA_RIS_RISC ( DIBA_RIS_ID ) ;

ALTER TABLE DIBA_DGC_DIAGNOSTIC ADD CONSTRAINT DIBA_DGC_DIAGNOSTIC_FK_EST FOREIGN KEY ( DIBA_DGC_ESTAT ) REFERENCES DIBA_EST_ESTAT ( DIBA_EST_ID ) ;

ALTER TABLE DIBA_DGC_DIAGNOSTIC ADD CONSTRAINT DIBA_DGC_DIAGNOSTIC_FK_EXP FOREIGN KEY ( DIBA_DGC_EXPEDIENT ) REFERENCES DIBA_EXP_EXPEDIENT ( DIBA_EXP_ID ) ;

ALTER TABLE DIBA_DGC_DIAGNOSTIC ADD CONSTRAINT DIBA_DGC_DIAGNOSTIC_FK_PRF FOREIGN KEY ( DIBA_DGC_PROFESSIONAL ) REFERENCES DIBA_PRF_PROFESSIONAL ( DIBA_PRF_ID ) ;

ALTER TABLE DIBA_DGC_DIAGNOSTIC ADD CONSTRAINT DIBA_DGC_DIAGNOSTIC_FK_VAL FOREIGN KEY ( DIBA_DGC_VALORACIO ) REFERENCES DIBA_VAL_VALORACIO ( DIBA_VAL_ID ) ;

ALTER TABLE DIBA_DGC_DIAGNOSTIC ADD CONSTRAINT DIBA_DGC_DIAGNOSTIC_FK_VSM FOREIGN KEY ( DIBA_DGC_VERSIO_MODEL ) REFERENCES DIBA_VSM_VERSIOMODEL ( DIBA_VSM_ID ) ;

ALTER TABLE DIBA_ECO_ECONOMIA ADD CONSTRAINT DIBA_ECO_ECONOMIA_FK_FAE FOREIGN KEY ( DIBA_ECO_FACTOR ) REFERENCES DIBA_FAE_FACTORECONOMIC ( DIBA_FAE_ID ) ;

ALTER TABLE DIBA_ECO_ECONOMIA ADD CONSTRAINT DIBA_ECO_ECONOMIA_FK_PRE FOREIGN KEY ( DIBA_ECO_PREGUNTA ) REFERENCES DIBA_PRE_PREGUNTA ( DIBA_PRE_ID ) ;

ALTER TABLE DIBA_ENT_ENTORN ADD CONSTRAINT DIBA_ENT_ENTORN_FK_AMB FOREIGN KEY ( DIBA_ENT_AMBIT ) REFERENCES DIBA_AMB_AMBIT ( DIBA_AMB_ID ) ;

ALTER TABLE DIBA_EXP_EXPEDIENT ADD CONSTRAINT DIBA_EXP_EXPEDIENT_FK_EST FOREIGN KEY ( DIBA_EXP_ESTAT ) REFERENCES DIBA_EST_ESTAT ( DIBA_EST_ID ) ;

ALTER TABLE DIBA_EXP_EXPEDIENT ADD CONSTRAINT DIBA_EXP_EXPEDIENT_FK_PRF FOREIGN KEY ( DIBA_EXP_PROFESSIONAL ) REFERENCES DIBA_PRF_PROFESSIONAL ( DIBA_PRF_ID ) ;

ALTER TABLE DIBA_FCT_FACTOR ADD CONSTRAINT DIBA_FCT_FACTOR_FK_AMB FOREIGN KEY ( DIBA_FCT_AMBIT ) REFERENCES DIBA_AMB_AMBIT ( DIBA_AMB_ID ) ;

ALTER TABLE DIBA_FCT_FACTOR ADD CONSTRAINT DIBA_FCT_FACTOR_FK_GRA FOREIGN KEY ( DIBA_FCT_GRAVETAT ) REFERENCES DIBA_GRA_GRAVETAT ( DIBA_GRA_ID ) ;

ALTER TABLE DIBA_FAE_FACTORECONOMIC ADD CONSTRAINT DIBA_FAE_FACTORECONOMIC_FK_VSM FOREIGN KEY ( DIBA_FAE_VERSIO_MODEL ) REFERENCES DIBA_VSM_VERSIOMODEL ( DIBA_VSM_ID ) ;

ALTER TABLE DIBA_FRG_FREQUENCIAGRAVETAT ADD CONSTRAINT DIBA_FRG_FK_GRA FOREIGN KEY ( DIBA_FRG_GRAVETAT ) REFERENCES DIBA_GRA_GRAVETAT ( DIBA_GRA_ID ) ;

ALTER TABLE DIBA_FRG_FREQUENCIAGRAVETAT ADD CONSTRAINT DIBA_FRG_FK_SSO FOREIGN KEY ( DIBA_FRG_SITUACIO_SOCIAL ) REFERENCES DIBA_SSO_SITUACIO_SOCIAL ( DIBA_SSO_ID ) ;

ALTER TABLE DIBA_PER_PERSONA ADD CONSTRAINT DIBA_PER_PERSONA_FK_EXP FOREIGN KEY ( DIBA_PER_EXPEDIENT ) REFERENCES DIBA_EXP_EXPEDIENT ( DIBA_EXP_ID ) ;

ALTER TABLE DIBA_PER_PERSONA ADD CONSTRAINT DIBA_PER_PERSONA_FK_TPE FOREIGN KEY ( DIBA_PER_TIPUS_PERSONA ) REFERENCES DIBA_TPE_TIPUSPERSONA ( DIBA_TPE_ID ) ;

ALTER TABLE DIBA_PRE_PREGUNTA ADD CONSTRAINT DIBA_PRE_PREGUNTA_FK_AMD FOREIGN KEY ( DIBA_PRE_AMBIT ) REFERENCES DIBA_AMD_AMBITDIAGNOSTIC ( DIBA_AMD_ID ) ;

ALTER TABLE DIBA_PRE_PREGUNTA ADD CONSTRAINT DIBA_PRE_PREGUNTA_FK_DGC FOREIGN KEY ( DIBA_PRE_DIAGNOSTIC ) REFERENCES DIBA_DGC_DIAGNOSTIC ( DIBA_DGC_ID ) ;

ALTER TABLE DIBA_PRE_PREGUNTA ADD CONSTRAINT DIBA_PRE_PREGUNTA_FK_FACTOR FOREIGN KEY ( DIBA_PRE_FACTOR ) REFERENCES DIBA_RIS_RISC ( DIBA_RIS_ID ) ;

ALTER TABLE DIBA_PRE_PREGUNTA ADD CONSTRAINT DIBA_PRE_PREGUNTA_FK_FRQ FOREIGN KEY ( DIBA_PRE_FREQUENCIA ) REFERENCES DIBA_FRQ_FREQUENCIA ( DIBA_FRQ_ID ) ;

ALTER TABLE DIBA_PRE_PREGUNTA ADD CONSTRAINT DIBA_PRE_PREGUNTA_FK_GRA FOREIGN KEY ( DIBA_PRE_GRAVETAT ) REFERENCES DIBA_GRA_GRAVETAT ( DIBA_GRA_ID ) ;

ALTER TABLE DIBA_PRE_PREGUNTA ADD CONSTRAINT DIBA_PRE_PREGUNTA_FK_PER FOREIGN KEY ( DIBA_PRE_PERSONA ) REFERENCES DIBA_PER_PERSONA ( DIBA_PER_ID ) ;

ALTER TABLE DIBA_PRE_PREGUNTA ADD CONSTRAINT DIBA_PRE_PREGUNTA_FK_RIS FOREIGN KEY ( DIBA_PRE_RISC ) REFERENCES DIBA_RIS_RISC ( DIBA_RIS_ID ) ;

ALTER TABLE DIBA_PRE_PREGUNTA ADD CONSTRAINT DIBA_PRE_PREGUNTA_FK_SSO FOREIGN KEY ( DIBA_PRE_SITUACIO_SOCIAL ) REFERENCES DIBA_SSO_SITUACIO_SOCIAL ( DIBA_SSO_ID ) ;

ALTER TABLE DIBA_PRF_PROFESSIONAL ADD CONSTRAINT DIBA_PRF_PROFESSIONAL_FK_MUN FOREIGN KEY ( DIBA_PRF_MUNICIPI ) REFERENCES DIBA_MUN_MUNICIPI ( DIBA_MUN_ID ) ;

ALTER TABLE DIBA_PRR_PROFESSIONAL_ROL ADD CONSTRAINT DIBA_PRR_FK_PRF FOREIGN KEY ( DIBA_PRR_PROFESSIONAL ) REFERENCES DIBA_PRF_PROFESSIONAL ( DIBA_PRF_ID ) ;

ALTER TABLE DIBA_PRR_PROFESSIONAL_ROL ADD CONSTRAINT DIBA_PRR_FK_ROL FOREIGN KEY ( DIBA_PRR_ROL ) REFERENCES DIBA_ROL_ROL ( DIBA_ROL_ID ) ;

ALTER TABLE DIBA_SSO_SITUACIO_SOCIAL ADD CONSTRAINT DIBA_SSO_FK_ENT FOREIGN KEY ( DIBA_SSO_ENTORN ) REFERENCES DIBA_ENT_ENTORN ( DIBA_ENT_ID ) ;

ALTER TABLE DIBA_SSO_SITUACIO_SOCIAL ADD CONSTRAINT DIBA_SSO_FK_VSM FOREIGN KEY ( DIBA_SSO_VERSIO_MODEL ) REFERENCES DIBA_VSM_VERSIOMODEL ( DIBA_VSM_ID ) ;
