CREATE TABLE DIBA_AMB_AMBIT
  (
    DIBA_AMB_ID                 NUMBER NOT NULL ,
    DIBA_AMB_DESCRIPCIO         VARCHAR2 (150) ,
    DIBA_AMB_VULNERABILITAT     NUMBER ,
    DIBA_AMB_RISC               NUMBER ,
    DIBA_AMB_VAL_VULNERABILITAT NUMBER ,
    DIBA_AMB_VAL_RISC           NUMBER ,
    DIBA_AMB_VAL_ALTRISC        NUMBER ,
    DIBA_AMB_OBSERVACIONS       VARCHAR2 (500) ,
    DIBA_AMB_VERSIO_MODEL       NUMBER NOT NULL
  ) ;


CREATE TABLE DIBA_AMD_AMBITDIAGNOSTIC
  (
    DIBA_AMD_ID           NUMBER NOT NULL ,
    DIBA_AMD_AMBIT        NUMBER NOT NULL ,
    DIBA_AMD_DIAGNOSTIC   NUMBER ,
    DIBA_AMD_OBSERVACIONS VARCHAR2 (250)
  ) ;


CREATE TABLE DIBA_AVL_AVALUACIO
  (
    DIBA_AVL_ID                NUMBER NOT NULL ,
    DIBA_AVL_RISC_PROFESSIONAL NUMBER ,
    DIBA_AVL_RISC              NUMBER ,
    DIBA_AVL_VALORACIO         NUMBER ,
    DIBA_AVL_AMBIT             NUMBER ,
    DIBA_AVL_JUSTIFICACIO      VARCHAR2 (250)
  ) ;


CREATE TABLE DIBA_CTX_CONTEXTUALITZACIO
  (
    DIBA_CTX_ID          NUMBER NOT NULL ,
    DIBA_CTX_DIAGNOSTIC  NUMBER NOT NULL ,
    DIBA_CTX_MEMBRE_UNIC CHAR (1) ,
    DIBA_CTX_MES_UC      CHAR (1) ,
    DIBA_CTX_PERSONA     NUMBER ,
    DIBA_CTX_FACTOR      NUMBER NOT NULL
  ) ;


CREATE TABLE DIBA_CRI_CRITERI
  (
    DIBA_CRI_ID                  NUMBER NOT NULL ,
    DIBA_CRI_EVIDENCIA           VARCHAR2 (500) ,
    DIBA_CRI_FREQUENCIA          NUMBER NOT NULL ,
    DIBA_CRI_RISC                NUMBER NOT NULL ,
    DIBA_CRI_FREQUENCIA_GRAVETAT VARCHAR2 (32) NOT NULL
  ) ;


CREATE TABLE DIBA_DGC_DIAGNOSTIC
  (
    DIBA_DGC_ID           NUMBER NOT NULL ,
    DIBA_DGC_DATA         TIMESTAMP WITH LOCAL TIME ZONE ,
    DIBA_DGC_OBSERVACIONS VARCHAR2 (250) ,
    DIBA_DGC_VERSIO_MODEL NUMBER ,
    DIBA_DGC_VALORACIO    NUMBER ,
    DIBA_DGC_EXPEDIENT    NUMBER ,
    DIBA_DGC_ESTAT        NUMBER ,
    DIBA_DGC_PROFESSIONAL NUMBER
  ) ;


CREATE TABLE DIBA_ECO_ECONOMIA
  (   
  	DIBA_ECO_FACTOR NUMBER NOT NULL , 
  	DIBA_ECO_PREGUNTA NUMBER NOT NULL
  ) ;


CREATE TABLE DIBA_ENT_ENTORN
  (
    DIBA_ENT_ID         NUMBER NOT NULL ,
    DIBA_ENT_DESCRIPCIO VARCHAR2 (250) ,
    DIBA_ENT_AMBIT      NUMBER NOT NULL
  ) ;


CREATE TABLE DIBA_EST_ESTAT
  ( 
  	DIBA_EST_ID NUMBER NOT NULL , 
  	DIBA_EST_DESCRIPCIO VARCHAR2 (50)
  ) ;


CREATE TABLE DIBA_EXP_EXPEDIENT
  (
    DIBA_EXP_ID             NUMBER NOT NULL ,
    DIBA_EXP_CODI           VARCHAR2 (50) NOT NULL ,
    DIBA_EXP_DATA_CREACIO   TIMESTAMP WITH LOCAL TIME ZONE ,
    DIBA_EXP_TOTAL_FAMILIA  NUMBER ,
    DIBA_EXP_PROFESSIONAL   NUMBER ,
    DIBA_EXP_TOTAL          NUMBER ,
    DIBA_EXP_DATA_VALIDACIO TIMESTAMP WITH LOCAL TIME ZONE ,
    DIBA_EXP_ESTAT          NUMBER ,
    DIBA_EXP_OBSERVACIONS   VARCHAR2 (500)
  ) ;


CREATE TABLE DIBA_FCT_FACTOR
  (
    DIBA_FCT_ID         NUMBER NOT NULL ,
    DIBA_FCT_GRAVETAT   NUMBER ,
    DIBA_FCT_DESCRIPCIO VARCHAR2 (300) ,
    DIBA_FCT_FC1M       NUMBER ,
    DIBA_FCT_FCTOTS     NUMBER ,
    DIBA_FCT_AMBIT      NUMBER ,
    DIBA_FCT_INFANTS    CHAR (1)
  ) ;


CREATE TABLE DIBA_FAE_FACTORECONOMIC
  (
    DIBA_FAE_ID           NUMBER NOT NULL ,
    DIBA_FAE_DESCRIPCIO   VARCHAR2 (300) ,
    DIBA_FAE_VERSIO_MODEL NUMBER NOT NULL
  ) ;


CREATE TABLE DIBA_FRQ_FREQUENCIA
  (
    DIBA_FRQ_ID         NUMBER NOT NULL ,
    DIBA_FRQ_DESCRIPCIO VARCHAR2 (100) ,
    DIBA_FRQ_VALUE      INTEGER
  ) ;


CREATE TABLE DIBA_FRG_FREQUENCIAGRAVETAT
  (
    DIBA_FRG_ID              VARCHAR2 (32) NOT NULL ,
    DIBA_FRG_SITUACIO_SOCIAL VARCHAR2 (32) NOT NULL ,
    DIBA_FRG_EVIDENCIA       VARCHAR2 (500) NOT NULL ,
    DIBA_FRG_GRAVETAT        NUMBER NOT NULL
  ) ;


CREATE TABLE DIBA_GRA_GRAVETAT
  (
    DIBA_GRA_ID         NUMBER NOT NULL ,
    DIBA_GRA_DESCRIPCIO VARCHAR2 (100) ,
    DIBA_GRA_VALUE      INTEGER
  ) ;


CREATE TABLE DIBA_MUN_MUNICIPI
  ( 
  	DIBA_MUN_ID NUMBER NOT NULL , 
  	DIBA_MUN_DESCRIPCIO VARCHAR2 (100)
  ) ;


CREATE TABLE DIBA_PER_PERSONA
  (
    DIBA_PER_ID             NUMBER NOT NULL ,
    DIBA_PER_SEXE           VARCHAR2 (10) ,
    DIBA_PER_DATA_NAIXEMENT TIMESTAMP WITH LOCAL TIME ZONE ,
    DIBA_PER_TIPUS_PERSONA  NUMBER ,
    DIBA_PER_REFERENCIA     CHAR (1) ,
    DIBA_PER_DATA_ALTA      TIMESTAMP WITH LOCAL TIME ZONE ,
    DIBA_PER_DATA_BAIXA     TIMESTAMP WITH LOCAL TIME ZONE ,
    DIBA_PER_EXPEDIENT      NUMBER
  ) ;


CREATE TABLE DIBA_PRE_PREGUNTA
  (
    DIBA_PRE_ID              NUMBER NOT NULL ,
    DIBA_PRE_DIAGNOSTIC      NUMBER ,
    DIBA_PRE_PERSONA         NUMBER ,
    DIBA_PRE_RISC            NUMBER ,
    DIBA_PRE_GRAVETAT        NUMBER ,
    DIBA_PRE_FREQUENCIA      NUMBER ,
    DIBA_PRE_SITUACIO_SOCIAL VARCHAR2 (32) ,
    DIBA_PRE_ENTORN          NUMBER ,
    DIBA_PRE_UNITAT_FAMILIAR CHAR (1) ,
    DIBA_PRE_FACTOR          NUMBER ,
    DIBA_PRE_AMBIT           NUMBER
  ) ;


CREATE TABLE DIBA_PRF_PROFESSIONAL
  (
    DIBA_PRF_ID          NUMBER NOT NULL ,
    DIBA_PRF_NOM         VARCHAR2 (100) ,
    DIBA_PRF_COGNOM1     VARCHAR2 (100) ,
    DIBA_PRF_COGNOM2     VARCHAR2 (100) ,
    DIBA_PRF_MUNICIPI    NUMBER NOT NULL ,
    DIBA_PRF_NOM_COMPLET VARCHAR2 (100),
    DIBA_PRF_USERNAME 	 VARCHAR2 (100),
    DIBA_PRF_PASSWORD 	 VARCHAR2 (100)
  ) ;


CREATE TABLE DIBA_PRR_PROFESSIONAL_ROL
  (
    DIBA_PRR_PROFESSIONAL NUMBER NOT NULL ,
    DIBA_PRR_ROL          NUMBER NOT NULL
  ) ;


CREATE TABLE DIBA_RIS_RISC
  (
    DIBA_RIS_ID         NUMBER NOT NULL ,
    DIBA_RIS_DESCRIPCIO VARCHAR2 (100) ,
    DIBA_RIS_VALUE      INTEGER
  ) ;


CREATE TABLE DIBA_ROL_ROL
  ( 
  	DIBA_ROL_ID NUMBER NOT NULL , 
  	DIBA_ROL_DESCRIPCIO VARCHAR2 (30),
  	DIBA_ROL_CODI NUMBER NOT NULL 
  ) ;


CREATE TABLE DIBA_SSO_SITUACIO_SOCIAL
  (
    DIBA_SSO_ID             VARCHAR2 (32) NOT NULL ,
    DIBA_SSO_SOCIAL         VARCHAR2 (500) ,
    DIBA_SSO_DEFINICIO      VARCHAR2 (600) ,
    DIBA_SSO_ENTORN         NUMBER NOT NULL ,
    DIBA_SSO_VULNERABILITAT NUMBER ,
    DIBA_SSO_RISC           NUMBER ,
    DIBA_SSO_ALT_RISC       NUMBER ,
    DIBA_SSO_VERSIO_MODEL   NUMBER NOT NULL
  ) ;


CREATE TABLE DIBA_TPE_TIPUSPERSONA
  ( 
  	DIBA_TPE_ID NUMBER NOT NULL , 
  	DIBA_TPE_DESCRIPCIO VARCHAR2 (50)
  ) ;


CREATE TABLE DIBA_VAL_VALORACIO
  (
    DIBA_VAL_ID        NUMBER NOT NULL ,
    DIBA_VAL_TOTAL     NUMBER ,
    DIBA_VAL_FACTORS   NUMBER ,
    DIBA_VAL_DATA      TIMESTAMP WITH LOCAL TIME ZONE ,
    DIBA_VAL_CONFIRMAT CHAR (1)
  ) ;


CREATE TABLE DIBA_VSM_VERSIOMODEL
  (
    DIBA_VSM_ID                 NUMBER NOT NULL ,
    DIBA_VSM_VERSIO             VARCHAR2 (20) ,
    DIBA_VSM_DATA               TIMESTAMP WITH LOCAL TIME ZONE ,
    DIBA_VSM_PREGUNTA_ECONOMICA NUMBER
  ) ;