DELETE FROM DIBA_AMB_AMBIT ;

DELETE FROM DIBA_AMD_AMBITDIAGNOSTIC ;

DELETE FROM DIBA_AVL_AVALUACIO ;

DELETE FROM DIBA_CTX_CONTEXTUALITZACIO ;

DELETE FROM DIBA_CRI_CRITERI ;

DELETE FROM DIBA_DGC_DIAGNOSTIC ;

DELETE FROM DIBA_ECO_ECONOMIA ;

DELETE FROM DIBA_ENT_ENTORN ;

DELETE FROM DIBA_EST_ESTAT ;

DELETE FROM DIBA_EXP_EXPEDIENT ;

DELETE FROM DIBA_FCT_FACTOR ;

DELETE FROM DIBA_FAE_FACTORECONOMIC ;

DELETE FROM DIBA_FRQ_FREQUENCIA ;

DELETE FROM DIBA_FRG_FREQUENCIAGRAVETAT ;

DELETE FROM DIBA_GRA_GRAVETAT ;

DELETE FROM DIBA_MUN_MUNICIPI ;

DELETE FROM DIBA_PER_PERSONA ;

DELETE FROM DIBA_PRE_PREGUNTA ;

DELETE FROM DIBA_PRF_PROFESSIONAL ;

DELETE FROM DIBA_PRR_PROFESSIONAL_ROL ;

DELETE FROM DIBA_RIS_RISC ;

DELETE FROM DIBA_ROL_ROL ;

DELETE FROM DIBA_SSO_SITUACIO_SOCIAL ;

DELETE FROM DIBA_TPE_TIPUSPERSONA ;

DELETE FROM DIBA_VAL_VALORACIO ;

DELETE FROM DIBA_VSM_VERSIOMODEL ;