DROP TABLE DIBA_AMB_AMBIT CASCADE CONSTRAINTS ;

DROP TABLE DIBA_AMD_AMBITDIAGNOSTIC CASCADE CONSTRAINTS ;

DROP TABLE DIBA_AVL_AVALUACIO CASCADE CONSTRAINTS ;

DROP TABLE DIBA_CTX_CONTEXTUALITZACIO CASCADE CONSTRAINTS ;

DROP TABLE DIBA_CRI_CRITERI CASCADE CONSTRAINTS ;

DROP TABLE DIBA_DGC_DIAGNOSTIC CASCADE CONSTRAINTS ;

DROP TABLE DIBA_ECO_ECONOMIA CASCADE CONSTRAINTS ;

DROP TABLE DIBA_ENT_ENTORN CASCADE CONSTRAINTS ;

DROP TABLE DIBA_EST_ESTAT CASCADE CONSTRAINTS ;

DROP TABLE DIBA_EXP_EXPEDIENT CASCADE CONSTRAINTS ;

DROP TABLE DIBA_FCT_FACTOR CASCADE CONSTRAINTS ;

DROP TABLE DIBA_FAE_FACTORECONOMIC CASCADE CONSTRAINTS ;

DROP TABLE DIBA_FRQ_FREQUENCIA CASCADE CONSTRAINTS ;

DROP TABLE DIBA_FRG_FREQUENCIAGRAVETAT CASCADE CONSTRAINTS ;

DROP TABLE DIBA_GRA_GRAVETAT CASCADE CONSTRAINTS ;

DROP TABLE DIBA_MUN_MUNICIPI CASCADE CONSTRAINTS ;

DROP TABLE DIBA_PER_PERSONA CASCADE CONSTRAINTS ;

DROP TABLE DIBA_PRE_PREGUNTA CASCADE CONSTRAINTS ;

DROP TABLE DIBA_PRF_PROFESSIONAL CASCADE CONSTRAINTS ;

DROP TABLE DIBA_PRR_PROFESSIONAL_ROL CASCADE CONSTRAINTS ;

DROP TABLE DIBA_RIS_RISC CASCADE CONSTRAINTS ;

DROP TABLE DIBA_ROL_ROL CASCADE CONSTRAINTS ;

DROP TABLE DIBA_SSO_SITUACIO_SOCIAL CASCADE CONSTRAINTS ;

DROP TABLE DIBA_TPE_TIPUSPERSONA CASCADE CONSTRAINTS ;

DROP TABLE DIBA_VAL_VALORACIO CASCADE CONSTRAINTS ;

DROP TABLE DIBA_VSM_VERSIOMODEL CASCADE CONSTRAINTS ;