GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_PRF_PROFESSIONAL  TO DSDIBA_ROL_MANT;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_AMB_AMBIT TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_AMD_AMBITDIAGNOSTIC TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_AVL_AVALUACIO TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_CTX_CONTEXTUALITZACIO TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_CRI_CRITERI TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_DGC_DIAGNOSTIC TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_ECO_ECONOMIA TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_ENT_ENTORN TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_EST_ESTAT TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_EXP_EXPEDIENT TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_FCT_FACTOR TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_FAE_FACTORECONOMIC TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_FRQ_FREQUENCIA TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_FRG_FREQUENCIAGRAVETAT TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_GRA_GRAVETAT TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_MUN_MUNICIPI TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_PER_PERSONA TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_PRE_PREGUNTA TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_PRF_PROFESSIONAL TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_PRR_PROFESSIONAL_ROL TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_RIS_RISC TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_ROL_ROL TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_SSO_SITUACIO_SOCIAL TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_TPE_TIPUSPERSONA TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_VAL_VALORACIO TO DSDIBA_ROL_MANT ;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIBA_VSM_VERSIOMODEL TO DSDIBA_ROL_MANT ;

GRANT SELECT ON DIBA_PRF_PROFESSIONAL  TO DSDIBA_ROL_CONS;

GRANT SELECT ON DIBA_AMB_AMBIT TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_AMD_AMBITDIAGNOSTIC TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_AVL_AVALUACIO TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_CTX_CONTEXTUALITZACIO TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_CRI_CRITERI TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_DGC_DIAGNOSTIC TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_ECO_ECONOMIA TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_ENT_ENTORN TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_EST_ESTAT TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_EXP_EXPEDIENT TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_FCT_FACTOR TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_FAE_FACTORECONOMIC TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_FRQ_FREQUENCIA TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_FRG_FREQUENCIAGRAVETAT TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_GRA_GRAVETAT TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_MUN_MUNICIPI TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_PER_PERSONA TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_PRE_PREGUNTA TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_PRF_PROFESSIONAL TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_PRR_PROFESSIONAL_ROL TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_RIS_RISC TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_ROL_ROL TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_SSO_SITUACIO_SOCIAL TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_TPE_TIPUSPERSONA TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_VAL_VALORACIO TO DSDIBA_ROL_CONS ;

GRANT SELECT ON DIBA_VSM_VERSIOMODEL TO DSDIBA_ROL_CONS ;

GRANT SELECT ON HIBERNATE_SEQUENCE TO DSDIBA_ROL_CONS;